name: Seattle Staging Deploy

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 1/1 * *'
    - cron: '0 12 1/1 * *'

permissions: read-all

# Two probers running at once can break each other.
concurrency:
  group: stagingenvironment
  cancel-in-progress: true

jobs:
  run_prober:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Deploy Seattle staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: bin/deploy -e staging -i civiform/civiform:latest

      - name: Run prober test
        env:
          TEST_USER_LOGIN: ${{ secrets.TEST_USER_LOGIN }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        run: bin/run-prober
      
      
#      re-add this to prover env      
#          RECORD_VIDEO: 1
#      - name: Save recorded video
#        uses: actions/upload-artifact@v3
#        with:
#          name: browser-test-videos
#          path: tmp/videos/
#          retention-days: 1
